Repository google/ground-android, pull requests merged in 2019-11, with the labels that each got.

#191 Use DataBinding in RecordListAdapter
  gnd/src/main/java/com/google/android/gnd/ui/common/AbstractFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/common/ViewModelModule.java
  gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/RecordListAdapter.java
  gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/RecordListFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/RecordListItemViewHolder.java
  gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/RecordViewModel.java
  gnd/src/main/res/layout/record_list_item.xml
  gnd/src/main/res/values/strings.xml
Labels: cla: yes

#198 Update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: cla: yes

#195 Integrate Google Cloud Build
  .gitignore
  README.md
  cloud-builder/Dockerfile-base
  cloud-builder/Dockerfile-sdk
  cloud-builder/cloudbuild.yaml
  cloudbuild.yaml
  gnd/build.gradle
  gnd/google-services.json
  gnd/src/main/AndroidManifest.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: cla: yes

#197 Remove/Revert BasemapSelectorMapAdapter
  build.gradle
  gnd/src/main/java/com/google/android/gnd/ui/basemapselector/BasemapSelectorFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/map/Extent.java
  gnd/src/main/java/com/google/android/gnd/ui/map/ExtentSelector.java
  gnd/src/main/java/com/google/android/gnd/ui/map/MapProvider.java
  gnd/src/main/java/com/google/android/gnd/ui/map/gms/BasemapSelectorMapAdapter.java
  gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsMapProvider.java
Labels: cla: yes

#201 Update launcher icon to latest "light" Material style
  gnd/src/main/ic_launcher-web.png
  gnd/src/main/res/drawable/ic_launcher_background.xml
  gnd/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  gnd/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  gnd/src/main/res/mipmap-hdpi/ic_launcher.png
  gnd/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  gnd/src/main/res/mipmap-hdpi/ic_launcher_round.png
  gnd/src/main/res/mipmap-mdpi/ic_launcher.png
  gnd/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  gnd/src/main/res/mipmap-mdpi/ic_launcher_round.png
  gnd/src/main/res/mipmap-xhdpi/ic_launcher.png
  gnd/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  gnd/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  gnd/src/main/res/mipmap-xxhdpi/ic_launcher.png
  gnd/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  gnd/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  gnd/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  gnd/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  gnd/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  gnd/src/main/res/values/ic_launcher_background.xml
Labels: cla: yes

#207 [Code health] Lint checks
  cloudbuild.yaml
  config/lint/lint.gradle
  config/lint/lint.xml
  gnd/build.gradle
  gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
Labels: cla: yes

#209 [Code health] Run static code analysis with PMD
  cloudbuild.yaml
  config/pmd/pmd-ruleset.xml
  config/pmd/pmd.gradle
  gnd/build.gradle
Labels: cla: yes

#194 Integrate firebase performance monitoring plugin
  build.gradle
  gnd/build.gradle
Labels: cla: yes

#200 [Code health] Checkstyle gradle plugin
  CONTRIBUTING.md
  cloudbuild.yaml
  config/checkstyle/checkstyle.gradle
  config/checkstyle/checkstyle.xml
  gnd/build.gradle
  gnd/src/main/java/com/google/android/gnd/MainViewModel.java
  gnd/src/main/java/com/google/android/gnd/inject/GndWorkerFactory.java
  gnd/src/main/java/com/google/android/gnd/persistence/local/room/LocalDatabase.java
  gnd/src/main/java/com/google/android/gnd/persistence/local/room/ResponseJsonConverter.java
  gnd/src/main/java/com/google/android/gnd/persistence/local/room/TileDao.java
  gnd/src/main/java/com/google/android/gnd/persistence/local/room/TileEntity.java
  gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java
  gnd/src/main/java/com/google/android/gnd/repository/InMemoryCache.java
  gnd/src/main/java/com/google/android/gnd/rx/RxCompletable.java
  gnd/src/main/java/com/google/android/gnd/system/PermissionsManager.java
  gnd/src/main/java/com/google/android/gnd/ui/MapIcon.java
  gnd/src/main/java/com/google/android/gnd/ui/basemapselector/BasemapSelectorFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/basemapselector/BasemapSelectorModule.java
  gnd/src/main/java/com/google/android/gnd/ui/basemapselector/BasemapSelectorViewModel.java
  gnd/src/main/java/com/google/android/gnd/ui/common/AbstractDialogFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/common/AbstractFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/common/BottomSheetBehavior.java
  gnd/src/main/java/com/google/android/gnd/ui/common/Navigator.java
  gnd/src/main/java/com/google/android/gnd/ui/common/SingleLiveEvent.java
  gnd/src/main/java/com/google/android/gnd/ui/common/TwoLineToolbar.java
  gnd/src/main/java/com/google/android/gnd/ui/common/UnswipeableViewPager.java
  gnd/src/main/java/com/google/android/gnd/ui/common/ViewModelFactory.java
  gnd/src/main/java/com/google/android/gnd/ui/editrecord/MultiSelectDialogFactory.java
  gnd/src/main/java/com/google/android/gnd/ui/editrecord/MultipleChoiceFieldLayout.java
  gnd/src/main/java/com/google/android/gnd/ui/editrecord/SingleSelectDialogFactory.java
  gnd/src/main/java/com/google/android/gnd/ui/home/BottomSheetChromeBehavior.java
  gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java
  gnd/src/main/java/com/google/android/gnd/ui/home/OnBottomSheetSlideBehavior.java
  gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerLayoutBehavior.java
  gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/projectselector/ProjectSelectorViewModel.java
  gnd/src/main/java/com/google/android/gnd/ui/signin/SignInFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/util/ViewUtil.java
  gnd/src/main/java/com/google/android/gnd/workers/FileDownloadWorkManager.java
  gnd/src/main/java/com/google/android/gnd/workers/FileDownloadWorker.java
Labels: cla: yes

#218 Fix minor lint warnings
  config/lint/lint.xml
  gnd/src/main/java/com/google/android/gnd/persistence/local/LocalValueStore.java
  gnd/src/main/res/layout/record_list_frag.xml
Labels: cla: yes

#219 Update README and CONTRIBUTING guidelines
  CONTRIBUTING.md
  README.md
Labels: cla: yes

#221 [Code health] Enable few PMD checks
  config/pmd/pmd-ruleset.xml
  gnd/src/main/java/com/google/android/gnd/model/observation/MultipleChoiceResponse.java
  gnd/src/main/java/com/google/android/gnd/model/observation/TextResponse.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FeatureDoc.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/GndFirestore.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/RecordDoc.java
  gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java
  gnd/src/main/java/com/google/android/gnd/system/AuthenticationManager.java
  gnd/src/main/java/com/google/android/gnd/ui/basemapselector/BasemapSelectorFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/common/AbstractDialogFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/common/BindingAdapters.java
  gnd/src/main/java/com/google/android/gnd/ui/common/BottomSheetBehavior.java
  gnd/src/main/java/com/google/android/gnd/ui/editrecord/EditRecordFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/editrecord/SingleSelectDialogFactory.java
  gnd/src/main/java/com/google/android/gnd/ui/home/AddFeatureDialogFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsMapAdapter.java
  gnd/src/main/java/com/google/android/gnd/ui/projectselector/ProjectSelectorDialogFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/recorddetails/RecordDetailsFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/recorddetails/RecordDetailsViewModel.java
  gnd/src/main/java/com/google/android/gnd/util/Enums.java
  gnd/src/main/java/com/google/android/gnd/workers/FileDownloadWorker.java
Labels: cla: yes, priority: p1, type: cleanup

#215 Fix broken record list, Rx schedulers, and cleanup
  gnd/src/main/java/com/google/android/gnd/persistence/local/LocalDataStore.java
  gnd/src/main/java/com/google/android/gnd/persistence/local/room/RecordDao.java
  gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/RemoteDataStore.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FirestoreDataStore.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/GndFirestore.java
  gnd/src/main/java/com/google/android/gnd/persistence/sync/LocalMutationSyncWorker.java
  gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java
  gnd/src/main/java/com/google/android/gnd/ui/editrecord/EditRecordViewModel.java
  gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java
  gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/RecordListAdapter.java
  gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/RecordListFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/RecordListItemViewHolder.java
  gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/RecordListViewModel.java
  gnd/src/main/java/com/google/android/gnd/ui/recorddetails/RecordDetailsViewModel.java
  gradle/wrapper/gradle-wrapper.properties
Labels: cla: yes

#222 [Code health] Add check for license headers
  config/checkstyle/checkstyle.gradle
  config/checkstyle/checkstyle.xml
  config/checkstyle/java.header
  config/checkstyle/xml.header
  gnd/src/main/java/com/google/android/gnd/model/basemap/tile/Tile.java
  gnd/src/main/java/com/google/android/gnd/persistence/local/room/TileDao.java
  gnd/src/main/java/com/google/android/gnd/persistence/local/room/TileEntity.java
  gnd/src/main/java/com/google/android/gnd/persistence/local/room/TileEntityState.java
  gnd/src/main/java/com/google/android/gnd/ui/basemapselector/BasemapSelectorFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/basemapselector/BasemapSelectorModule.java
  gnd/src/main/java/com/google/android/gnd/ui/basemapselector/BasemapSelectorViewModel.java
  gnd/src/main/res/layout/basemap_selector_frag.xml
  gnd/src/main/res/layout/edit_record_frag.xml
  gnd/src/main/res/layout/feature_sheet_chrome.xml
  gnd/src/main/res/layout/home_screen_frag.xml
  gnd/src/main/res/layout/main_act.xml
  gnd/src/main/res/layout/multiple_choice_input_field.xml
  gnd/src/main/res/layout/project_selector_dialog.xml
  gnd/src/main/res/layout/project_selector_list_item.xml
  gnd/src/main/res/layout/record_details_frag.xml
  gnd/src/main/res/layout/sign_in_frag.xml
  gnd/src/main/res/layout/text_input_field.xml
  gnd/src/main/res/layout/two_line_toolbar.xml
Labels: cla: yes

#225 [Code health] Check format of Javadoc summary
  config/checkstyle/checkstyle.xml
  gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java
  gnd/src/main/java/com/google/android/gnd/ui/common/BottomSheetBehavior.java
  gnd/src/main/java/com/google/android/gnd/ui/common/EphemeralPopups.java
  gnd/src/main/java/com/google/android/gnd/ui/common/ProgressDialogs.java
Labels: cla: yes

#224 [Bug] Fix a regression caused during code health refactor
  gnd/src/main/java/com/google/android/gnd/ui/common/BottomSheetBehavior.java
Labels: cla: yes

#227 Update README
  README.md
Labels: cla: yes

#226 [Code health] Spotbugs plugin
  README.md
  build.gradle
  cloudbuild.yaml
  config/spotbugs/spotbugs-filter.xml
  config/spotbugs/spotbugs.gradle
  gnd/build.gradle
Labels: cla: yes, priority: p2, type: cleanup, type: process

#228 [Code health] Add gradle task checkCode
  README.md
  build.gradle
  cloudbuild.yaml
Labels: cla: yes

#229 [Documentation] Add troubleshooting section
  README.md
Labels: cla: yes

#233 [Code health] Enable excluded checks for spotbugs
  config/spotbugs/spotbugs-filter.xml
Labels: cla: yes, priority: p2, type: cleanup, type: process

#231 [Refactor] Rename key concepts
  gnd/src/main/java/com/google/android/gnd/MainActivityModule.java
  gnd/src/main/java/com/google/android/gnd/model/Mutation.java
  gnd/src/main/java/com/google/android/gnd/model/Project.java
  gnd/src/main/java/com/google/android/gnd/model/feature/Feature.java
  gnd/src/main/java/com/google/android/gnd/model/layer/Layer.java
  gnd/src/main/java/com/google/android/gnd/model/observation/Observation.java
  gnd/src/main/java/com/google/android/gnd/model/observation/ObservationMutation.java
  gnd/src/main/java/com/google/android/gnd/model/observation/ResponseDelta.java
  gnd/src/main/java/com/google/android/gnd/persistence/local/LocalDataStore.java
  gnd/src/main/java/com/google/android/gnd/persistence/local/room/FeatureEntity.java
  gnd/src/main/java/com/google/android/gnd/persistence/local/room/FeatureMutationEntity.java
  gnd/src/main/java/com/google/android/gnd/persistence/local/room/RecordDao.java
  gnd/src/main/java/com/google/android/gnd/persistence/local/room/RecordEntity.java
  gnd/src/main/java/com/google/android/gnd/persistence/local/room/RecordMutationEntity.java
  gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/RemoteDataStore.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FeatureDoc.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FirestoreDataStore.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/GndFirestore.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/LayerDoc.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/ObservationDoc.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/ProjectDoc.java
  gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java
  gnd/src/main/java/com/google/android/gnd/ui/common/BindingAdapters.java
  gnd/src/main/java/com/google/android/gnd/ui/common/Navigator.java
  gnd/src/main/java/com/google/android/gnd/ui/common/ViewModelModule.java
  gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationModule.java
  gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationViewModel.java
  gnd/src/main/java/com/google/android/gnd/ui/editobservation/MultiSelectDialogFactory.java
  gnd/src/main/java/com/google/android/gnd/ui/editobservation/MultipleChoiceFieldLayout.java
  gnd/src/main/java/com/google/android/gnd/ui/editobservation/SingleSelectDialogFactory.java
  gnd/src/main/java/com/google/android/gnd/ui/home/AddFeatureDialogFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java
  gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/FeatureSheetFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/FeatureSheetViewModel.java
  gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/FormTabPagerAdapter.java
  gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/ObservationListAdapter.java
  gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/ObservationListFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/ObservationListItemViewHolder.java
  gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/ObservationListViewModel.java
  gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/ObservationViewModel.java
  gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsMapAdapter.java
  gnd/src/main/java/com/google/android/gnd/ui/observationdetails/ObservationDetailsFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/observationdetails/ObservationDetailsModule.java
  gnd/src/main/java/com/google/android/gnd/ui/observationdetails/ObservationDetailsViewModel.java
  gnd/src/main/res/layout/edit_observation_frag.xml
  gnd/src/main/res/layout/multiple_choice_input_field.xml
  gnd/src/main/res/layout/observation_details_field.xml
  gnd/src/main/res/layout/observation_details_frag.xml
  gnd/src/main/res/layout/observation_list_frag.xml
  gnd/src/main/res/layout/observation_list_item.xml
  gnd/src/main/res/layout/text_input_field.xml
  gnd/src/main/res/menu/observation_details_menu.xml
  gnd/src/main/res/navigation/nav_graph.xml
  gnd/src/main/res/values-pt/strings.xml
  gnd/src/main/res/values/dimens.xml
  gnd/src/main/res/values/strings.xml
Labels: cla: yes

#232 [Code health] Enable check for unused imports
  config/pmd/pmd-ruleset.xml
  gnd/src/main/java/com/google/android/gnd/ui/common/SharedViewModel.java
  gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
Labels: cla: yes, priority: p2, type: cleanup, type: process

#234 [Code health] Add cloud build badge to README
  README.md
  build.gradle
  cloud-builder/failure.svg
  cloud-builder/success.svg
  cloudbuild.yaml
Labels: cla: yes

#239 [CI] Suppress failure if reports were not generated
  cloudbuild.yaml
Labels: cla: yes

#237 Clean up third_party dependencies
  config/checkstyle/checkstyle.gradle
  settings.gradle
  third_party/android-gmaps-addons/AndroidManifest.xml
  third_party/android-gmaps-addons/LICENSE
  third_party/android-gmaps-addons/METADATA
  third_party/android-gmaps-addons/build.gradle
  third_party/android-gmaps-addons/src/com/cocoahero/android/gmaps/addons/mapbox/MapBoxOfflineTileProvider.java
  third_party/android-gmaps-addons/src/com/cocoahero/android/gmaps/addons/mapbox/MapBoxOnlineTileProvider.java
  third_party/checkstyle/LICENSE
  third_party/checkstyle/METADATA
  third_party/checkstyle/google_checks.xml
Labels: cla: yes
