Repository google/ground-android, pull requests merged in 2020-01, with the labels that each got.

#291 [Offline sync] Fix broken observation mutation sync
  gnd/src/main/java/com/google/android/gnd/persistence/local/room/ObservationMutationDao.java
  gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java
Labels: cla: yes

#295 [Auth] Fix exception on failed sign in
  gnd/src/main/java/com/google/android/gnd/MainActivity.java
  gnd/src/main/java/com/google/android/gnd/system/AuthenticationManager.java
  gnd/src/main/java/com/google/android/gnd/ui/common/Navigator.java
Labels: cla: yes

#283 [Code Health] Replace deprecated SingleLiveEvent with Event<> wrapper
  gnd/src/main/java/com/google/android/gnd/rx/Action.java
  gnd/src/main/java/com/google/android/gnd/rx/Event.java
  gnd/src/main/java/com/google/android/gnd/ui/common/SingleLiveEvent.java
  gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationViewModel.java
  gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java
Labels: cla: yes

#284 [Code health] Fix feature stream
  gnd/src/main/java/com/google/android/gnd/MainViewModel.java
  gnd/src/main/java/com/google/android/gnd/repository/FeatureRepository.java
Labels: cla: yes

#287 Offline area download button
  gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
  gnd/src/main/res/drawable-anydpi/ic_area_download.xml
  gnd/src/main/res/drawable-hdpi/ic_area_download.png
  gnd/src/main/res/drawable-mdpi/ic_area_download.png
  gnd/src/main/res/drawable-xhdpi/ic_area_download.png
  gnd/src/main/res/drawable-xxhdpi/ic_area_download.png
  gnd/src/main/res/layout/offline_areas_frag.xml
  gnd/src/main/res/values/strings.xml
  gnd/src/main/res/values/styles.xml
Labels: cla: yes

#302 Project loading error
  gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
Labels: cla: yes

#304 [Offline sync] Fix storing loading project offline
  .idea/codeStyles/Project.xml
  gnd/build.gradle
  gnd/src/main/java/com/google/android/gnd/GndApplication.java
  gnd/src/main/java/com/google/android/gnd/MainActivity.java
  gnd/src/main/java/com/google/android/gnd/model/Timestamps.java
  gnd/src/main/java/com/google/android/gnd/model/layer/Layer.java
  gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/RemoteDataStore.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FirestoreDataStore.java
  gnd/src/main/java/com/google/android/gnd/repository/ProjectRepository.java
  gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationViewModel.java
  gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
Labels: cla: yes

#315 Location lock priority and related tweaks
  gnd/build.gradle
  gnd/src/main/java/com/google/android/gnd/GndApplication.java
  gnd/src/main/java/com/google/android/gnd/system/LocationManager.java
Labels: cla: yes

#318 [Support Photos] Add field type photo
  gnd/src/main/java/com/google/android/gnd/Config.java
  gnd/src/main/java/com/google/android/gnd/model/form/Field.java
  gnd/src/main/java/com/google/android/gnd/persistence/local/room/FieldEntityType.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FormDoc.java
  gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationFragment.java
Labels: cla: yes

#324 [Project list] Fix loading of project list when offline
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/AbstractFluentFirestore.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/GndFirestore.java
  gnd/src/main/java/com/google/android/gnd/rx/RxCompletable.java
  gnd/src/main/java/com/google/android/gnd/system/GoogleApiManager.java
  gnd/src/main/java/com/google/android/gnd/system/NetworkManager.java
  gnd/src/main/java/com/google/android/gnd/system/PermissionsManager.java
  gnd/src/main/java/com/google/android/gnd/system/SettingsManager.java
Labels: cla: yes

#319 [Support Photos] UI templates for Photo field
  gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationViewModel.java
  gnd/src/main/res/drawable/ic_add_a_photo.xml
  gnd/src/main/res/layout/photo_input_field.xml
  gnd/src/main/res/values/strings.xml
Labels: cla: yes

#311 [Support Photos] Integrate Firebase Storage for uploading photos
  gnd/build.gradle
  gnd/src/main/java/com/google/android/gnd/persistence/remote/FirestoreStorageManager.java
Labels: cla: yes

#320 [Code health] Run code health checks on build
  cloudbuild.yaml
  gnd/build.gradle
Labels: cla: yes

#316 [Project selector] Fix reappearing frozen project selector
  gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/projectselector/ProjectSelectorDialogFragment.java
Labels: cla: yes

#329 Revert "[Project selector] Fix reappearing frozen project selector"
  gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/projectselector/ProjectSelectorDialogFragment.java
Labels: cla: yes, priority: p0, type: bug

#330 Dismiss project selector
  gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/projectselector/ProjectSelectorDialogFragment.java
Labels: cla: yes

#325 [Code health] Remove unused remote database fields
  gnd/src/main/java/com/google/android/gnd/model/form/Form.java
  gnd/src/main/java/com/google/android/gnd/persistence/local/room/FormEntity.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FormDoc.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/LayerDoc.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/ProjectDoc.java
  gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/FormTabPagerAdapter.java
  gnd/src/main/java/com/google/android/gnd/ui/observationdetails/ObservationDetailsViewModel.java
  gnd/src/main/res/layout/observation_details_frag.xml
Labels: cla: yes

#331 [Code health] Enforce default statement in switch-case
  gnd/src/main/java/com/google/android/gnd/MainActivity.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FeatureDoc.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/ObservationDoc.java
  gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/ObservationListItemViewHolder.java
  gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/observationdetails/ObservationDetailsFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/projectselector/ProjectSelectorDialogFragment.java
  third_party/checkstyle/google_checks.xml
Labels: cla: yes, priority: p2, type: cleanup

#326 [Code health] Tidy up fluent Firestore base classes
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/AbstractFluentFirestore.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/GndFirestore.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/base/FluentCollectionReference.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/base/FluentDocumentReference.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/base/FluentFirestore.java
  gnd/src/main/java/com/google/android/gnd/system/NetworkManager.java
Labels: cla: yes

#333 [Code health] Tweak license header check
  config/checkstyle/checkstyle.gradle
  config/checkstyle/xml.header
  gnd/src/main/AndroidManifest.xml
  gnd/src/main/res/color/field_label.xml
  gnd/src/main/res/color/field_value.xml
  gnd/src/main/res/drawable-anydpi/ic_area_download.xml
  gnd/src/main/res/drawable-anydpi/ic_cloud_offline.xml
  gnd/src/main/res/drawable/feature_header_icon_background_drawable.xml
  gnd/src/main/res/drawable/ic_add_a_photo.xml
  gnd/src/main/res/drawable/ic_launcher_background.xml
  gnd/src/main/res/drawable/launch_screen.xml
  gnd/src/main/res/layout/edit_observation_frag.xml
  gnd/src/main/res/layout/feature_sheet_chrome.xml
  gnd/src/main/res/layout/feature_sheet_frag.xml
  gnd/src/main/res/layout/feature_sheet_header.xml
  gnd/src/main/res/layout/home_screen_frag.xml
  gnd/src/main/res/layout/main_act.xml
  gnd/src/main/res/layout/map_container_frag.xml
  gnd/src/main/res/layout/multiple_choice_input_field.xml
  gnd/src/main/res/layout/nav_drawer_header.xml
  gnd/src/main/res/layout/observation_details_field.xml
  gnd/src/main/res/layout/observation_details_frag.xml
  gnd/src/main/res/layout/observation_list_frag.xml
  gnd/src/main/res/layout/observation_list_item.xml
  gnd/src/main/res/layout/offline_area_selector_frag.xml
  gnd/src/main/res/layout/offline_areas_frag.xml
  gnd/src/main/res/layout/photo_input_field.xml
  gnd/src/main/res/layout/project_selector_dialog.xml
  gnd/src/main/res/layout/project_selector_list_item.xml
  gnd/src/main/res/layout/sign_in_frag.xml
  gnd/src/main/res/layout/startup_frag.xml
  gnd/src/main/res/layout/text_input_field.xml
  gnd/src/main/res/layout/two_line_toolbar.xml
  gnd/src/main/res/menu/feature_sheet_menu.xml
  gnd/src/main/res/menu/nav_drawer_menu.xml
  gnd/src/main/res/menu/observation_details_menu.xml
  gnd/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  gnd/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  gnd/src/main/res/navigation/nav_graph.xml
  gnd/src/main/res/values-pt/strings.xml
  gnd/src/main/res/values-v19/styles.xml
  gnd/src/main/res/values-v21/styles.xml
  gnd/src/main/res/values/attrs.xml
  gnd/src/main/res/values/colors.xml
  gnd/src/main/res/values/dimens.xml
  gnd/src/main/res/values/font_certs.xml
  gnd/src/main/res/values/ic_launcher_background.xml
  gnd/src/main/res/values/strings-untranslated.xml
  gnd/src/main/res/values/strings.xml
  gnd/src/main/res/values/styles.xml
Labels: cla: yes, priority: p2, type: cleanup

#339 Update API key comment
  gnd/src/main/AndroidManifest.xml
Labels: cla: yes

#338 [Code health] Minor cleanup of Rx wrappers
  gnd/src/main/java/com/google/android/gnd/MainViewModel.java
  gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FirestoreDataStore.java
  gnd/src/main/java/com/google/android/gnd/repository/FeatureRepository.java
  gnd/src/main/java/com/google/android/gnd/repository/ProjectRepository.java
  gnd/src/main/java/com/google/android/gnd/repository/UserRepository.java
  gnd/src/main/java/com/google/android/gnd/rx/BooleanOrError.java
  gnd/src/main/java/com/google/android/gnd/rx/Loadable.java
  gnd/src/main/java/com/google/android/gnd/rx/RxDebug.java
  gnd/src/main/java/com/google/android/gnd/rx/RxLocationServices.java
  gnd/src/main/java/com/google/android/gnd/rx/Schedulers.java
  gnd/src/main/java/com/google/android/gnd/system/LocationManager.java
  gnd/src/main/java/com/google/android/gnd/system/SettingsManager.java
  gnd/src/main/java/com/google/android/gnd/system/rx/RxFusedLocationProviderClient.java
  gnd/src/main/java/com/google/android/gnd/system/rx/RxLocationCallback.java
  gnd/src/main/java/com/google/android/gnd/system/rx/RxSettingsClient.java
  gnd/src/main/java/com/google/android/gnd/ui/home/AddFeatureDialogFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java
  gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerViewModel.java
  gnd/src/main/java/com/google/android/gnd/ui/observationdetails/ObservationDetailsFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/observationdetails/ObservationDetailsViewModel.java
  gnd/src/main/java/com/google/android/gnd/ui/projectselector/ProjectSelectorDialogFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/projectselector/ProjectSelectorViewModel.java
Labels: cla: yes

#335 [Cleanup] Split up GndDirestore
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/AuditInfoDoc.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FirestoreDataStore.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/GndFirestore.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/converters/QuerySnapshotConverter.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/FeatureDocumentReference.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/FeaturesCollectionReference.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/GroundFirestore.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/ProjectDocumentReference.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/ProjectsCollectionReference.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/RecordDocumentReference.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/RecordsCollectionReference.java
Labels: cla: yes
