Repository google/ground-android, pull requests merged in 2020-03, with the labels that each got.

#379 [Feature] Display active project in navigation drawer
  .idea/codeStyles/Project.xml
  gnd/src/main/java/com/google/android/gnd/repository/ProjectRepository.java
  gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/projectselector/ProjectSelectorDialogFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/projectselector/ProjectSelectorViewModel.java
  gnd/src/main/res/color/nav_drawer_item.xml
  gnd/src/main/res/layout/home_screen_frag.xml
  gnd/src/main/res/menu/nav_drawer_menu.xml
  gnd/src/main/res/values-pt/strings.xml
  gnd/src/main/res/values/strings.xml
Labels: cla: yes

#390 Misc. Improvements to Support Offline Areas
  gnd/src/main/java/com/google/android/gnd/inject/GndWorkerFactory.java
  gnd/src/main/java/com/google/android/gnd/ui/map/MapProvider.java
  gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsMapAdapter.java
  gnd/src/main/java/com/google/android/gnd/workers/TileDownloadWorkManager.java
  gnd/src/main/java/com/google/android/gnd/workers/TileDownloadWorker.java
Labels: cla: yes

#391 Use Apache Commons in GeoJsonParser; Fix GeoJsonExtent
  gnd/build.gradle
  gnd/src/main/java/com/google/android/gnd/persistence/geojson/GeoJsonExtent.java
  gnd/src/main/java/com/google/android/gnd/persistence/geojson/GeoJsonParser.java
Labels: cla: yes

#394 Allow null styles in remote db
  gnd/src/main/java/com/google/android/gnd/persistence/local/room/StyleTypeConverter.java
Labels: cla: yes

#395 Bump up gradle version
  build.gradle
  gnd/src/main/res/layout/feature_sheet_header.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: cla: yes

#398 [Code-health] Add task for dependency check to Cloud Build
  build.gradle
  gnd/build.gradle
Labels: cla: yes

#397 [Maintenance] Update non-conflicting gradle dependencies
  gnd/build.gradle
Labels: cla: yes

#399 [Code health] Add dependency health badge to README
  README.md
  build.gradle
  cloud-builder/dependency.svg
  cloud-builder/generate_dependency_health_svg.py
  cloudbuild.yaml
Labels: cla: yes

#392 Refactor Tile Download Worker to Download Pending Tiles in DB
  gnd/src/main/java/com/google/android/gnd/persistence/local/LocalDataStore.java
  gnd/src/main/java/com/google/android/gnd/persistence/local/room/RoomLocalDataStore.java
  gnd/src/main/java/com/google/android/gnd/persistence/local/room/TileDao.java
  gnd/src/main/java/com/google/android/gnd/workers/TileDownloadWorkManager.java
  gnd/src/main/java/com/google/android/gnd/workers/TileDownloadWorker.java
Labels: cla: yes

#385 [Map] Refactor map adapter
  gnd/src/main/java/com/google/android/gnd/model/feature/Point.java
  gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java
  gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerViewModel.java
  gnd/src/main/java/com/google/android/gnd/ui/map/MapAdapter.java
  gnd/src/main/java/com/google/android/gnd/ui/map/MapPin.java
  gnd/src/main/java/com/google/android/gnd/ui/map/MapProvider.java
  gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsMapAdapter.java
  gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsMapProvider.java
  gnd/src/main/java/com/google/android/gnd/ui/offlinearea/selector/OfflineAreaSelectorFragment.java
Labels: cla: yes

#386 [Photos Support] Improve upload photo UI
  .idea/codeStyles/Project.xml
  gnd/src/main/java/com/google/android/gnd/persistence/remote/FirestoreStorageManager.java
  gnd/src/main/java/com/google/android/gnd/system/StorageManager.java
  gnd/src/main/java/com/google/android/gnd/ui/common/BindingAdapters.java
  gnd/src/main/java/com/google/android/gnd/ui/common/ViewModelModule.java
  gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationViewModel.java
  gnd/src/main/java/com/google/android/gnd/ui/editobservation/PhotoDialogFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/editobservation/PhotoFieldViewModel.java
  gnd/src/main/java/com/google/android/gnd/ui/observationdetails/ObservationDetailsFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/util/FileUtil.java
  gnd/src/main/res/layout/photo_input_field.xml
  gnd/src/main/res/values/dimens.xml
  gnd/src/main/res/values/strings.xml
Labels: cla: yes

#401 [Cleanup] Replace manual subscription handling with ViewModel
  gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/editobservation/PhotoFieldViewModel.java
  gnd/src/main/java/com/google/android/gnd/ui/observationdetails/ObservationDetailsFragment.java
  gnd/src/main/res/layout/observation_details_field.xml
  gnd/src/main/res/layout/photo_field.xml
  gnd/src/main/res/layout/photo_input_field.xml
Labels: cla: yes

#402 Clean up MapAdapter
  gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsMapAdapter.java
Labels: cla: yes

#403 [Cleanup] Fix cloudbuild config
  cloudbuild.yaml
Labels: cla: yes

#407 Update dependencies
  build.gradle
  gnd/build.gradle
  gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/FeatureSheetFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/home/featuresheet/ObservationListFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerFragment.java
Labels: cla: yes

#404 [Photos] Sync photos to FirebaseStorage using Workers
  gnd/src/main/java/com/google/android/gnd/Config.java
  gnd/src/main/java/com/google/android/gnd/GndApplication.java
  gnd/src/main/java/com/google/android/gnd/GndApplicationModule.java
  gnd/src/main/java/com/google/android/gnd/inject/GndWorkerFactory.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/FirestoreStorageManager.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/RemoteStorageManager.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FirestoreStorageManager.java
  gnd/src/main/java/com/google/android/gnd/persistence/sync/LocalMutationSyncWorker.java
  gnd/src/main/java/com/google/android/gnd/persistence/sync/PhotoSyncWorkManager.java
  gnd/src/main/java/com/google/android/gnd/persistence/sync/PhotoSyncWorker.java
  gnd/src/main/java/com/google/android/gnd/repository/FeatureRepository.java
  gnd/src/main/java/com/google/android/gnd/system/StorageManager.java
  gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationViewModel.java
Labels: cla: yes, priority: p1, type: feature request

#410 [Cleanup] Use DataBinding for TwoLineToolbar
  gnd/src/main/java/com/google/android/gnd/ui/common/TwoLineToolbar.java
  gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/observationdetails/ObservationDetailsFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/observationdetails/ObservationDetailsViewModel.java
  gnd/src/main/res/layout/edit_observation_frag.xml
  gnd/src/main/res/layout/feature_sheet_chrome.xml
  gnd/src/main/res/layout/observation_details_frag.xml
  gnd/src/main/res/layout/two_line_toolbar.xml
Labels: cla: yes

#414 [Notifications] Show notifications when uploading photos
  gnd/src/main/java/com/google/android/gnd/inject/GndWorkerFactory.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/RemoteStorageManager.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/UploadProgress.java
  gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/FirestoreStorageManager.java
  gnd/src/main/java/com/google/android/gnd/persistence/sync/PhotoSyncWorker.java
  gnd/src/main/java/com/google/android/gnd/system/NotificationManager.java
  gnd/src/main/res/drawable/ic_sync.xml
  gnd/src/main/res/values/strings.xml
Labels: cla: yes

#406 [Feature] Add button to switch map type
  gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerFragment.java
  gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerViewModel.java
  gnd/src/main/java/com/google/android/gnd/ui/map/MapAdapter.java
  gnd/src/main/java/com/google/android/gnd/ui/map/MapProvider.java
  gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsMapAdapter.java
  gnd/src/main/java/com/google/android/gnd/ui/map/gms/GoogleMapsMapProvider.java
  gnd/src/main/res/drawable/map_layers.xml
  gnd/src/main/res/layout/map_container_frag.xml
  gnd/src/main/res/values/strings.xml
Labels: cla: yes, type: feature request
